### ISSUE TITLE
chat settings improvements

### ISSUE THREAD

**Issue by ceanugula** [SubscribeIT/ngDesk#106]
**List of steps**
- [x]  Add teams who can chat, maximum number of chats,timings to chat settings.
- [x]  Get rid of roles who can chat.
- [x] Handle in ui

**Test criteria**
- [x]  Test thoroughly by posting new company
- [x] Make sure everything works

**Comment by reddy95** [comment]
when we save custom Teams , these custom teams are not showing in chat setting  drop down list
