### ISSUE TITLE
Create/ Edit Tickets - Data is not populated when date/ time is primary display field for a relationship field.

### ISSUE THREAD

**Issue by skatapady** [SubscribeIT/ngDesk#128]
- [ ] :large_orange_diamond:  **Create/ edit tickets** - Data for **date/ time** field as 'primary display field' is not populated in the create/ edit layout, even though data is present. PFA screenshot.

we have created a relationship field of type one to one in tickets module, related to contacts module and primary display field is date_updated, display field are Email, Date_updated and source type.

Issue is observed when primary display field is **button, date, time, approval, aggregate, file upload, file preview, image upload, zoom, address** (city, pin code, country, street 1 and street 2)

we can remove fields which are not required from **primary display field**.

Issue is also observed in **'Custom Module'**. This needs to be tested for **one to one, one to many, and many to many relationship field types**.

**Steps:**

1. Login to dev1.ngdesk.com with valid credentials by using chrome
1. click on modules on sidebar --> tickets --> fields --> create new relationship field
1. select the Contacts module >to select the primary display field as 'Date_Updated'
1. Relationship type should be one to one.
1. display field (you should click on Email, Date_Updated, source type)
1. fill all required fields --> click on save--> add field to create and edit layouts in system admin role
1. create contacts data with valid values in Email.
1. go back to tickets --> new button.

click and verify the date/time relationship field created in above steps

**Screenshot.**

![Screenshot from 2021-08-25 17-09-04](https://user-images.githubusercontent.com/89504195/131498125-a1f19b8a-7b7c-478e-8b4c-d2f718b6146a.png)
![Screenshot from 2021-08-25 17-05-02](https://user-images.githubusercontent.com/89504195/131498139-dc7a3c2e-956b-499a-bd13-a76efdc5d996.png)
![Screenshot from 2021-08-25 17-03-49](https://user-images.githubusercontent.com/89504195/131498146-907d1455-ad08-44f9-aa6c-83d1dae11b68.png)
![Screenshot from 2021-08-25 17-01-29](https://user-images.githubusercontent.com/89504195/131498150-875c3b2a-6706-426f-a291-cf459fe98eae.png)

**Comment by abs-ravi** [comment]
Completed:-

- Created custom module and tested with all senario mentioned above issue points.
- reported to @karthikbalu1 


**Conclusion:-**

- button:- its used for just triggering workflow. Its not storing any value in DB.
- date, time:- can handle need info
- approval:- Its saving as object in DB
- aggregate:- its aggregating two fields not storing value in Db(not storing any data in DB to display as primary display)
- file upload :- Its saving as object in DB
- file preview:- Its saving as object in DB
-  image upload:- Its saving as object in DB
-  zoom :- its  a button to join zoom meeting (not storing any data in DB to display as primary display)

- Can disable these fields from list of primary display fields
