### ISSUE TITLE
Create List Layout - 500 Internal server Error is displayed on page load when field 'System_Name' consist of spaces

### ISSUE THREAD

**Issue by skatapady** [SubscribeIT/ngDesk#141]
**Create List Layout** - Application is returning following error when user clicks on new button in the list layout.

500 - Internal Server Error

We observed that validation was missing for 'System_Label'  while creating a relationship field. PFA screenshot.

**Steps:**

1. logon to dev1.ngdesk.com
2. click on the modules --> tickets --> fields --> new button.
3. enter valid display label.
4. select data type as relationship field.
5. click on the next button.
6. select modules as 'accounts'
7. select relationship field type as one to one
8. select primary display for accounts as account name
9. select primary display for tickets as ID.
10. enter display label as book_id
11. update system label as BOOK_ID id
12. click on the 'save' button.
13. click on the modules --> tickets --> Layouts --> List Layout --> new button.

verify the error.

we expect proper error message to be displayed when the field is created.

**Screenshot**

![Screenshot from 2021-09-02 09-23-52](https://user-images.githubusercontent.com/89504195/131798774-ca6f6a92-1899-4ba9-89de-02efed9026f8.png)

![Screenshot from 2021-09-02 09-46-08](https://user-images.githubusercontent.com/89504195/131798818-693f1876-2833-44eb-b14c-add072fc276e.png)

![Screenshot from 2021-09-02 09-41-03](https://user-images.githubusercontent.com/89504195/131798821-01baf748-268b-4e43-b106-023891a0dfc7.png)

![Screenshot from 2021-09-02 09-40-43](https://user-images.githubusercontent.com/89504195/131798824-730d28d4-4f7a-422f-9b82-a2d5caa3c8b7.png)

**Comment by abs-ravi** [comment]
### Not able to replicate issue as mentioned in above steps:-

- Relationshipfield in ticket module

![Screenshot from 2021-09-03 10-29-23](https://user-images.githubusercontent.com/89505098/131958136-526212dc-74ef-4aaf-9afc-aa739572fcf9.png)
![Screenshot from 2021-09-03 10-29-04](https://user-images.githubusercontent.com/89505098/131958137-842df845-d268-4b5a-a335-a75a4ed771aa.png)

- Ticket module List layout
![Screenshot from 2021-09-03 10-30-08](https://user-images.githubusercontent.com/89505098/131958287-2d3a11db-6db4-4765-984d-3632db2ef0e5.png)

- Custom module
![Screenshot from 2021-09-03 10-32-41](https://user-images.githubusercontent.com/89505098/131958326-2f39713c-1dfa-459e-96ae-4e11b6eccc2d.png)
![Screenshot from 2021-09-03 10-32-27](https://user-images.githubusercontent.com/89505098/131958330-5953856c-08eb-4e2a-aa59-ce6b19bb3dc7.png)
![Screenshot from 2021-09-03 10-32-19](https://user-images.githubusercontent.com/89505098/131958332-2a575eb6-f729-45e3-a819-588ed20d38ea.png)

- Tested In prod account
![Screenshot from 2021-09-03 11-24-38](https://user-images.githubusercontent.com/89505098/131958389-b0f09a6d-56e3-423e-aca7-9283f617df4c.png)
![Screenshot from 2021-09-03 11-24-14](https://user-images.githubusercontent.com/89505098/131958395-a95bc2b0-7d5f-49c1-9d3b-93c0e8c3eb94.png)
![Screenshot from 2021-09-03 11-24-01](https://user-images.githubusercontent.com/89505098/131958397-27dfd5fd-26c4-444f-9532-e435020a253a.png)

**Comment by abs-ravi** [comment]
**Completed:-**

- Restricted the space for system label
- Reached out to devops team


**Todo:-**
- Not able to generate api getting errors while serving web
- need to test once the issue will resolved by devops

**Screenshots:-**
![image](https://user-images.githubusercontent.com/89505098/132000672-dc1ea8a5-6b25-48f3-a64d-86d8bdf5c9a0.png)

**Comment by unagireddy** [comment]
Issue got resloved  and followed the steps
Tested by creating a one to one relationship filed in tickets module .and added same to web_list_layout and no error (5oo internal server error )
Issue got fixed
TIme spend 2Hrs
