### ISSUE TITLE
Create/ Edit Module Data - tool tip for field with data type as 'File Upload' is partially visible when polaced in Left most Column

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#146]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

:large_blue_diamond: **Create/ Edit Module Data** - Tool tip is partially displayed for fields with data type as 'file upload'. This is observed when file upload file is displayed on left most column. This is also observed in tickets layout.

**List of Steps:**

1. navigate to dev1.ngdesk.com with valid 'SystemAdmin' credentials.
1. create field with the data type as 'File Upload' with 'help text' value greater than 30 chars) in the tickets module. (or any other module)
1. add it to create/ edit layouts.
1. click on Tickets sidebar menu --> new button.
1. move the mouse/ cursor on tool-tip for field with data type as 'File Upload'

**Screenshot**

![31](https://user-images.githubusercontent.com/89504119/131949812-705a5287-9110-499f-9643-8f11769f20ec.png)

![32](https://user-images.githubusercontent.com/89504119/131949799-0a283e9f-5220-4e73-8eac-65f0bcc4a508.png)

**Test Criteria:**

**Comment by sdthengil** [comment]
Performed below steps while testing.

1.Created an file upload data type field for ticket module and added in create & edit layout.
2.created an new ticket 
3.observed that tool tip is fully visible when mouse is moved over it.
4.Also added file upload data type field for default modules and observed that tool tip text is fully visible when mouse is moved over added.
5.Created an custom module with file upload data type(added more than 30 char in help text) field in create & edit layout
6.observed that tool tip text is fully visible when mouse is move over it.

issue is fixed.

/spend 3h

**Comment by sharath-satish** [comment]
Resolve Conflicts

**Comment by AyushAllBlue** [comment]
Fixed merge conflicts and tested again

![Screenshot from 2021-11-19 10-03-01](https://user-images.githubusercontent.com/89504119/142565394-99e32265-a799-4896-a131-90d64e66ce2f.png)
