### ISSUE TITLE
Escalations get calls to be replaced with graphql calls in the UI

### ISSUE THREAD

**Issue by phaneendraar** [SubscribeIT/ngDesk#147]
**Owner:** @phaneendraar  

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngDesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**
escalations list, escalations render

**General Description/Overview:**
Need to replace the escalations get calls with graphql calls

**List of Steps:**

- [ ] Replace the escalations get calls with graphql calls

**Test Criteria:**

- [ ] make sure the graphql calls work with no issue

**Comment by 11swarajmohanty** [comment]
Completed: In escalations-master.component.ts changed the get calls to graphql calls in the UI. Also made the sortBy working for Schedules as well in the UI.
Todo: In escalations-detail.component.ts changed the get calls to graphql calls in the UI.

**Comment by 11swarajmohanty** [comment]
Completed: In escalations-detail.component.ts changed the get calls to graphql calls in the UI, but the escalations details are not fetching. 
Todo: Need to change to uppercase all the query params so as to get escalations details and test it.
