### ISSUE TITLE
Remove unwanted code from the Render component

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#152]
**Owner:** @karthikbalu1 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 

- ngdesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

As a TYPE_OF_USER_OR_ROLE, I want SOME_GOAL so that SOME_REASON_OR_BENEFIT.

**List of Steps:**
- Remove unwanted code from the Render component

**Test Criteria:**

**Comment by apriya22** [comment]
* issue is fixed in production and dev

**Comment by karthikbalu1** [comment]
Since issue is already fixed, this issue will be closed.
