### ISSUE TITLE
Getting null pointer exception while evaluating formula field

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#156]
**Owner:** @karthikbalu1 
**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-Data-Service

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

- While formula field is being evaluated, a null pointer exception is being occurred.

**List of Steps:**

- [x]  Add a null check for that.

**Test Criteria:**

- [x] Null pointer exception shouldn't occur.

**Screenshot:**

![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/89620702/132161369-403d775d-4a47-428d-87a5-c51f030571be.png)

**Comment by unagireddy** [comment]
Testing done by creating and editing the contact and  by posting new company with  expenses .
Not observed any null pointer exception.
Issue got fixed
/time Spend : 2 hours
