### ISSUE TITLE
chats improvement On Page load - entry created 

### ISSUE THREAD

**Issue by knramya** [SubscribeIT/ngDesk#164]
**Owner:** @shashank5259 

**Task Type:** 
- [x] New 
- [ ] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):**  ngdesk-websocket

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

On Page load
- [ ] Chat entryshould be created by using data service(feign) and trigger workflow.

**List of Steps:**

**Test Criteria:**

**Comment by dharanids** [comment]
* Added Code

 TODO :        

*Testing
