### ISSUE TITLE
Edit Layout - Events from workflows / SLAs are not displayed in events page.

### ISSUE THREAD

**Issue by kkumar1995** [SubscribeIT/ngDesk#178]
**Owner:** @sharath-satish 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

**Edit Custom Module** - Events from **SLA/ Workflows** are not displayed in Events page. But it is displayed under 'Discussion' field events.

**List of Steps:**

1. logon to subdomain.ngdesk.com using chrome and with 'SystemAdmin' credentials.
2. create a custom module with following fields types.

Address, Aggregate, Approval, Auto Number, Button, Checkbox, Chronometer, Currency, Date, Date/Time, Discussion, Email, File Upload, File Preview, Formula, Image, List Text, Number, Phone, Picklist, Picklist (Multi-Select), Relationship, Text, Text Area, Time, URL, Workflow Stages, Zoom

3. add the fields created in above step to create / edit layout.
4. add the module to sidebar.
5. create a workflow with update entry node (to update a text field with any value)
6. create a SLA with 'Make a phone call' node.
7. create one records meeting the conditions in the SLA. (in custom module data)
8. create one records meeting the conditions in the Workflow. (in custom module data)
9. In the list layout, click on the same record, (created in step 7 or step 8)

verify the events message under discussion field.

10. click on the 'events button.

verify the events message

**Screenshot**

**Events Page**

![events1](https://user-images.githubusercontent.com/89504408/132832140-5f283c54-593a-44d1-9e61-78bfbd20ef12.png)
![events2](https://user-images.githubusercontent.com/89504408/132832155-3f5ebde9-4617-492c-869f-07fea3ff792b.png)

**Under Discussion Field (events)**

![events3](https://user-images.githubusercontent.com/89504408/132832211-cb44133d-923f-4971-b211-8ec5632350a8.png)
![events4](https://user-images.githubusercontent.com/89504408/132832215-2b8eb0b2-a929-4ce0-bb89-4d4afb2abb44.png)

**Test Criteria:**

**Comment by AyushAllBlue** [comment]
Done :- 

- Created new module.
- Added different fields to it.
- Added those fields to create/edit layout.
- Added that module to sidebar.
- Created workflow and sla with update entry node/make phone call node.
- Goto -> new module -> new.
- Create entry.
- Goto -> entry by clicking in list layout.
- Goto -> events.
- Observe the events related to workflow and SLA's.


![Screenshot from 2021-09-13 09-51-13](https://user-images.githubusercontent.com/89504119/133023544-c0454720-3b8b-4bf9-a27a-10b5e4c6fde7.png)

**Comment by AyushAllBlue** [comment]
Issue is already fixed

**Comment by AyushAllBlue** [comment]
Issue is already fixed

**Comment by unagireddy** [comment]
Issue is not getting replicated and tested like
Created an discussion field in the  module and added for list and edit layout 
And then created workflow and SLA'S
And added modules to the side bar 
And then created a new entry .Added requried data .and then saved it and get the record into edit mode and then checked whether the events are getting generated
same steps are done for existing modules as well
No issue is observed
Issue got fixed 

Time spend: 4 hours

**Comment by karthikbalu1** [comment]
Since issue is not replicated, and its already fixed. The issue will be closed.
