### ISSUE TITLE
One to one relationship type  bug

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#183]
**Owner:** @karthikbalu1 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngdesk-data

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

As a TYPE_OF_USER_OR_ROLE, I want SOME_GOAL so that SOME_REASON_OR_BENEFIT.
- For the relationship type  one to one,  it could be assigned to several entries instead of one entry.
- Screenshots:
![Screenshot from 2021-09-14 11-31-00](https://user-images.githubusercontent.com/89620702/133203394-c96e2ea4-5ee1-4668-ab7e-422e819755f7.png)
![Screenshot from 2021-09-14 11-31-06](https://user-images.githubusercontent.com/89620702/133203398-549448bc-9024-4510-b8dd-1f30fdc9d4d1.png)
![Screenshot from 2021-09-14 11-31-12](https://user-images.githubusercontent.com/89620702/133203403-1fc9a5f4-ebab-42b2-b359-ecf708e8c27b.png)

**List of Steps:**

- [ ] One to one relationship type should work properly.

**Test Criteria:**

- [ ] Tested one to one relationship type field.

**Comment by abs-ravi** [comment]
**Completed:-**

- Added the code for validation ,One to One relationship datatype if the field used in other entry throwing error.
- Tested with categories and users module
- Tested with using postman

**Todo:-**

- Need to test in custom module 
- Will create MR

**Screenshots**

![Screenshot from 2021-09-14 16-45-00](https://user-images.githubusercontent.com/89505098/133248437-4fd4871a-94cb-4c83-858d-b7283d3bcef4.png)
![Screenshot from 2021-09-14 16-43-48](https://user-images.githubusercontent.com/89505098/133248451-bdaaef68-e08a-4f14-8fac-a0b245a16cd1.png)
![Screenshot from 2021-09-14 16-43-01](https://user-images.githubusercontent.com/89505098/133248455-c92b3284-e055-4a5a-8ca9-8b1f7d05a485.png)

**Comment by unagireddy** [comment]
Testcase 1,2,3,4,5 are tested
Posted a new company with expenses and ticketing plugins
created two  new expenses with GL Code  in expenses in sidebar 
created categories with reguried field and add same GLcode for two categories and observed the error "The glcode may have been used in other existing entry, please try again".
Created the  new users in user .and entering same contact id in the contact filed which give a popup like " the contact id which already used for other user"
Same had observed in postman with the url and payload taken from the network
Created new module and relation ship filed and added same filed to edit and list layout
Created new users and added same contact id and observed the error
All the test cases got fixed
time spend :2 hours

**Comment by unagireddy** [comment]
Tested all the above 5 testcases
After changes done everything is working fine
follwed the steps like

1.Posted a new company with expenses and ticketing plugins
2.Created two new expenses with GL Code in expenses in sidebar
3.Created categories with reguried field and add same GLcode for two categories and observed the error "The glcode may have been used in other existing entry, please try again".
4.Created the new users in user .and entering same contact id in the contact filed which give a popup like " the contact id which already used for other user"
5.Same had observed in postman with the url and payload taken from the network
6.Created new module and relation ship filed and added same filed to edit and list layout
7.Created new users and added same contact id and observed the error
8.All the test cases got fixed
time spend :3 hours
