### ISSUE TITLE
Create/ Edit SLA - Application is returning 500 Error on selecting Bussiness Rules/ Hours

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#19]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

Create/ Edit SLA - application is returning following error on adding/ selecting a Business Hour/ Rules. PFA screenshot.

**List of Steps:**

1. logon to subdomain.ngdesk.com using valid 'SystemAdmin' user credentials.
2. click on Modules --> Products --> SLA --> new button.
3. enter valid data for name, description.
4. click on the plus icon under meet all conditions.
5. Select field as 'Product Name' operator as 'Contains' and value as 'Error'
6. Select Violation conditions as 'Currency' operator as 'Has Been' , value as 'Afghani Afghani'  and SLA expiry as 2.
7. select the Business Hours checkbox.
8. click on save in the pop-up window. (by default first option will be selected)
9. click on the plus icon under Actions.
10. Select Stop Escalations.
11. click on the 'save' button.

verify the error.

**Screenshot**

![18](https://user-images.githubusercontent.com/89504119/130952493-7df8aff7-4f6a-466b-a0ad-4b59ddd9a916.png)
![19](https://user-images.githubusercontent.com/89504119/130952495-ba9c7fe3-5a9e-4af1-b0e9-156da50b30a7.png)
![20](https://user-images.githubusercontent.com/89504119/130952500-5d1bcd15-33b7-4241-866a-fa4269b1bd59.png)
![21](https://user-images.githubusercontent.com/89504119/130952503-ccb2d0fe-9f79-4987-bbde-5e94cb6223c1.png)

**Test Criteria:**

**Comment by arepallipriyanka** [comment]
issue not replicated, close issue.
