### ISSUE TITLE
Action items is not loading

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#190]
**Owner:** @karthikbalu1 
**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngdesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

- There is a error in console, check and resolve it
![Screenshot from 2021-09-16 08-56-08](https://user-images.githubusercontent.com/89620702/133545049-c633577a-49e3-4b73-9ddb-6420a1d79374.png)

**List of Steps:**

**Test Criteria:**

- [ ] My action items should load properly.

**Comment by apriya22** [comment]
COMPLETED

* tested Action items by creating entry for tickets
* Page load without any error in console
* checked in Prod and main branch , works fine

![Screenshot from 2021-09-16 10-52-01](https://user-images.githubusercontent.com/89504219/133567182-f13b9538-aa9f-4559-86bd-9f0eb20e2894.png)
![Screenshot from 2021-09-16 10-52-25](https://user-images.githubusercontent.com/89504219/133567188-a34f0525-d0f4-40fa-8663-98c9092b7ec5.png)

**Comment by apriya22** [comment]
COMPLETED

* If change Request plugin is not posted while posting company then Actions items doesnt load as Change Request module is 
not present
* Tried to fix it from frontend by giving null filter didnt work
* checkking from BE

TODO

* Action items should lead without change Request plugin also

**Comment by apriya22** [comment]
COMPLETED

* Its not an issue 
* If plugins is posted then only action items are displayed

**Comment by karthikbalu1** [comment]
By default change request plugin will be present if new companies are posted.
