### ISSUE TITLE
Module validation

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#192]
**Owner:** @karthikbalu1 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngdesk-Module-Service

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

While creating a new module, without providing singular/plural module name it is being created.
Screenshot:

![Screenshot from 2021-09-16 12-31-16](https://user-images.githubusercontent.com/89620702/133565954-0c2223d9-f655-4524-a526-a9ce584c938d.png)
![Screenshot from 2021-09-16 12-30-44](https://user-images.githubusercontent.com/89620702/133565978-d7dcf6bb-7e15-4987-b72f-c7c5fb565e5e.png)

**List of Steps:**

- [ ] Add validation to validate both singular and plural module name.

**Test Criteria:**

- [ ] Test whether the validation is working.

**Comment by sdthengil** [comment]
perform below steps while testing.

1.module is not getting created if we do not give Module Name,Singular Name and Plural name.
2.proper error is getting displayed if we don't provide Module ,Singular and Plural name.
3.Module is getting created on providing Module,Singular and Plural Name.
4.Also did Backend/API testing which works successfully.

issue is fixed.
/spend 3h
