### ISSUE TITLE
Complete Chat Feature

### ISSUE THREAD

**Issue by sharath-satish** [SubscribeIT/ngDesk#195]

**Comment by ceanugula** [comment]
Improved chat option
* Whenever an user selects a chat option a publish from ui to backend is done which will set the chat status in the user session.
* User removal from sessions is moved to sessions job.
* On click of profile button on the tool bar, a publish from ui to backend takes place, which in turn fetch the status from the user 
  session and publish it back to the ui . In this way the status is retained.
* Adding time stamp to redis using epoch.

**Comment by skatapady** [comment]
- [ ] **2. Chat Settings** - Teams available to the chats should be filtered. Currently we observed that following teams were allowed in the drop down.
 Customer, Personal Teams of users, Public, Ghost.

We expect only **allowed teams** to be displayed in the  teams drop down.

**Steps:**

1. logon to dev1.ngdesk.com using valid 'systemAdmin' user credentials.
2. click on the company settings --> Chat settings
3. click on the teams drop down and verify the data

**Screenshot**

![Screenshot from 2021-09-23 15-30-19](https://user-images.githubusercontent.com/89504195/134488822-02386821-dedc-4a5c-b643-f3c678a87384.png)

![Screenshot from 2021-09-23 15-30-06](https://user-images.githubusercontent.com/89504195/134488924-df755282-3731-4e2e-9e4d-1622c4559587.png)

**Comment by ceanugula** [comment]
Filtered Ghost and public team from teams who can chat

**Comment by knramya** [comment]
* Tested Notifications are sent for sales and systemAdmin .

SystemAdmin

![Screenshot from 2021-09-27 16-52-00](https://user-images.githubusercontent.com/89504314/134900118-eafc54a4-2926-48a2-b367-958d63db6a42.png)

Sales

![Screenshot from 2021-09-27 16-48-09](https://user-images.githubusercontent.com/89504314/134900124-b519174f-4605-4776-827b-a34d0527ba22.png)

**Comment by skatapady** [comment]
- [ ] 3. **Chat Settings** - In a new company, in the chat settings page on page load 'teams' data is empty.  PFA screenshot.

**Steps:**

1. logon to dev1.ngdesk.com using valid 'systemAdmin' user credentials.
2. click on the company settings --> Chat settings
3. verify the teams data


**Screenshot**

![Screenshot from 2021-09-29 12-19-12](https://user-images.githubusercontent.com/89504195/135220031-576db729-9430-4bfa-a8b4-d457f084a3b1.png)

**Comment by skatapady** [comment]
/spend 2h

re opening the issue due to issue mentioned in point 3.

**Comment by skatapady** [comment]
- [ ] 4. **Post Company** - When user post company with 'Chats' plugin, by default chat module should be added in the sidebar menu.

We observed that currently users have to manually add the chats module to the sidebar menu.

**Steps:**

1. post a new company with Chats plugin on local.
2. logon to subdomain.ngdesk.com using valid admin credentials.
3. verify the sidebar menu.

**Comment by skatapady** [comment]
- [ ] 5. **Edit Chat Layout** - More space should be added between **Personal Details** Label and icon.
We expect it to be similar to other menu header like Technology, History, Chat history, Visited Pages.

**Steps:**

1. post a new company with Chats plugin on local.
2. logon to subdomain.ngdesk.com using valid admin credentials. 
3. click on company settings --> chat settings
4. add admin user to teams
5. click on company settings -- sidebar customization -- role
6. add chat modules to sidebar.
7. click on chat sidebar
8. click on existing chat (if no chat exists open chat widget and start chatting)
9. verify the Personal details icon and label


**Screenshot**

![Screenshot from 2021-11-10 15-04-01](https://user-images.githubusercontent.com/89504195/141088534-b4ddbbc9-6018-4a88-b8ef-f27c38150871.png)

**Comment by skatapady** [comment]
- [ ] 6. **Chat List Layout and Edit Chat Layout** - Application is returning following error when an agent user clicks on chat list layout. We also observed that edit layout for any chat is not loading. Even data in chat list layout is not displayed (like chat id )

Access restricted

We have enabled chat for the agent teams.

**Steps:**

1. post a company with Chats plugin
2. login as admin
3. create agent user
4. click on the company settings --> chat settings--> add admin, agent teams to chat
5. create sidebar for agent and admin user
6. login as agent user 
7. click on the chat sidebar and observed the error.
8. click on any existing chat and observe the error


**Screenshot**

![Screenshot from 2021-11-11 14-51-58](https://user-images.githubusercontent.com/89504195/141273149-dcab40f1-a20c-429d-940b-e2e135f49d8a.png)

![Screenshot from 2021-11-11 14-57-30](https://user-images.githubusercontent.com/89504195/141273188-36d32d27-173e-4ea5-9679-d6ffe09ed637.png)

![Screenshot from 2021-11-11 15-02-56](https://user-images.githubusercontent.com/89504195/141274139-88becd06-be41-440d-9f6b-4069a2f757d3.png)

![Screenshot from 2021-11-11 15-03-17](https://user-images.githubusercontent.com/89504195/141274195-3f06f9b4-4df0-4d35-aaf6-9dec2ff89c8f.png)

**Comment by skatapady** [comment]
- [ ] 7. **Edit Chat** - Time is not displayed  according to the set timezone in the subdomain. we have set timezone as Asia/Kolkata in the chat settings and in general settings. when current time is 3:11 PM it is displayed as 8:41 PM in the edit chat layout.

**Steps:**

1. post a company with Chats plugin
2. login as admin
3. enable chat for admin user
4. click on accepts chat for admin user
5. open chat widget and start chatting
6. observe the time zone in chat window and edit layout.

**Screenshot**

![Screenshot from 2021-11-11 15-13-58](https://user-images.githubusercontent.com/89504195/141275984-089269b9-7fc1-4bef-8cad-1735ae6837ee.png)

![Screenshot from 2021-11-11 15-11-13](https://user-images.githubusercontent.com/89504195/141275994-d2bbc64a-227f-4665-9697-2649bdf50ed8.png)

![Screenshot from 2021-11-11 15-15-32](https://user-images.githubusercontent.com/89504195/141276057-997a7935-9bb0-4f27-b020-2f94cd5c26cf.png)

![Screenshot from 2021-11-11 15-15-27](https://user-images.githubusercontent.com/89504195/141276065-b5eac474-bcc2-4f60-b89f-ed890f4508dc.png)

**Data Service** 

![Screenshot from 2021-11-11 15-19-21](https://user-images.githubusercontent.com/89504195/141276619-c4f4b913-fb46-4c69-aae6-f59b23814b2b.png)

**Comment by skatapady** [comment]
re opening the issue

**Comment by skatapady** [comment]
- [ ] 7. **WebSocket** - Following Exception is displayed in Websocket service console. It is continuously returning following error.

skThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.NullPointerException
	at com.ngdesk.websocket.SocketHandler.afterConnectionEstablished(SocketHandler.java:163)
	at com.ngdesk.websocket.SocketHandler$$FastClassBySpringCGLIB$$2a4de41.invoke(<generated>)


**Screenshot**

![Screenshot from 2021-11-17 11-16-55](https://user-images.githubusercontent.com/89504195/142142265-748e1814-d0ab-46a4-827d-56f2dea95bcc.png)

**Comment by skatapady** [comment]
- [ ] 8. **Notification** - all the old Notifications should be marked as read (or cleared) when user clicks on the latest notification.

**Steps:**

1. post a company with Chats plugin
2. logon to subdomain enable chat for agent/ admins
3. add chats to sidebar
4. accept chats by agent
5. send 4 chats by opening chat-widget
6. in agent login, click on the latest notification (one on the top)
7. check the notification 

last 3 notifications are still marked as unread.


**Screenshot**

**User sends 4 chats message**

![Screenshot from 2021-11-17 11-25-12](https://user-images.githubusercontent.com/89504195/142143181-77aabb30-436d-4747-8e6c-1b4fdeb64155.png)

**Agent Clicks on latest notification** (first from the top)

![Screenshot from 2021-11-17 11-25-17](https://user-images.githubusercontent.com/89504195/142143179-6bf98e61-2010-465c-8c1b-ac8962e8e4ab.png)

**Last three notification are not marked as read**

![Screenshot from 2021-11-17 11-25-26](https://user-images.githubusercontent.com/89504195/142143170-2380a552-7674-4f6b-b334-7a44bbcc8ad5.png)

**Comment by skatapady** [comment]
- 

>     * [x]  5. **Edit Chat Layout** - More space should be added between **Personal Details** Label and icon.
>       We expect it to be similar to other menu header like Technology, History, Chat history, Visited Pages.
> 
> 
> **Steps:**
> 
>     1. post a new company with Chats plugin on local.
> 
>     2. logon to subdomain.ngdesk.com using valid admin credentials.
> 
>     3. click on company settings --> chat settings
> 
>     4. add admin user to teams
> 
>     5. click on company settings -- sidebar customization -- role
> 
>     6. add chat modules to sidebar.
> 
>     7. click on chat sidebar
> 
>     8. click on existing chat (if no chat exists open chat widget and start chatting)
> 
>     9. verify the Personal details icon and label
> 
> 
> **Screenshot**
> 
> ![Screenshot from 2021-11-10 15-04-01](https://user-images.githubusercontent.com/89504195/141088534-b4ddbbc9-6018-4a88-b8ef-f27c38150871.png)

Issue is fixed.

![Screenshot from 2021-11-17 12-41-32](https://user-images.githubusercontent.com/89504195/142151159-833b8e25-b947-49d4-8cb3-df0bbb3f3043.png)

**Comment by skatapady** [comment]
new issue is logged for teams restriction in following issue.

https://github.com/SubscribeIT/ngDesk/issues/291

**Comment by skatapady** [comment]
- [ ] 9. **Chat Filters** - we observed that when agent clicks on another user chat user with status 'offine' is displayed even though the filter was applied as status=chatting.

Steps:

1. post company with Chats plugin
2. got to company settings --> chat settings --> add teams as agent and admin
3. Click on the accept chats for admin and agent
4. open 3 chat widget  in different browsers and start chatting.
5. close one chat window 
6. in agent login, add filter status = chatting (for all conditions)
7. click on any other 'users' chat message

we observed that users with status as offline is displayed even though the filter is applied.

**Screenshot**

![Screenshot from 2021-11-17 14-18-53](https://user-images.githubusercontent.com/89504195/142169007-061249f2-2432-434a-8576-a780e63ab2c2.png)

**Comment by skatapady** [comment]
- [ ] 10. **Edit Chat Layout** - Pre-made response is not displayed in the format it is saved. Formatting needs to be updated in edit chats and chat-widgets.

**Steps:**

1. post a company with Chats plugin
2. create a pre-made response (with formatting as in screenshot)
3. add agent teams to chat
4. open widgget and start chatting
5. in agent login, select premade response created in step2

verify the formatting'\

**Screenshot**  

![Screenshot from 2021-11-17 15-30-37](https://user-images.githubusercontent.com/89504195/142179820-e32e902d-29be-46a1-90b3-c4b658b3d26e.png)

![Screenshot from 2021-11-17 15-30-28](https://user-images.githubusercontent.com/89504195/142179830-447224f0-a426-440c-9538-d068de3bf7d3.png)

**Comment by skatapady** [comment]
- [ ] 11. **Business Hours** - We have enabled chats during 3:30 PM to 4:00 PM. we have closed all existing chat. and again opened a chat widget at 4:05 PM. notification is sent to agent users and users able to chat without any issues.

**Steps:**

1. post a company with Chats plugin
2. click on comany settings --> chat settings --> business hours 
3. set time as 3:30 PM to 4:00 PM
4. add agent to chat and enable max users to chat as 1.
5. save the settings
6. send chat after 4:00 PM (like 4:06 PM)

we observed that chat was enabled outside chat hours.

**Screenshot**

![Screenshot from 2021-11-17 16-07-18](https://user-images.githubusercontent.com/89504195/142185555-73abdfda-6365-41fe-bcde-147175b2c6cd.png)

![Screenshot from 2021-11-17 16-07-12](https://user-images.githubusercontent.com/89504195/142185559-a3de4735-3d48-49b6-b3df-c9f8d49c4319.png)

![Screenshot from 2021-11-17 16-06-50](https://user-images.githubusercontent.com/89504195/142185563-708da88e-2402-4114-a9e8-31c84740dfc5.png)

**Comment by skatapady** [comment]
re opening the issue due to issues mentioned in point 7,8,9,10,11.

**Comment by skatapady** [comment]
- [ ] 12. Chats - when customer closes the chat window and rejoins within 1 minutes, new chat window is displayed for admin/ agent/ sales users and empty chat window is displayed for the customer. (chat history is empty)

new chat window should be displayed  when customer rejoins after 1 minute. we expect both customer and agent user to use same window on which they were chatting before closing the chat window. (we expect chat history to be present if user rejoins withing 1 minute)

**Steps**

1. post a company with Chats plugin
2. logon as admin user
3. click on company settings --> chat settings -- add admin / agent teams
4. click on the accept chat button
5. open chat-widget and start chatting with admin
6. close that chat widget window.
7. rejoin within 55 seconds.
8. observed that chat history is empty in chat-widget and new chat edit layout is displayed for same user.

**Comment by skatapady** [comment]
- [ ] 12. Data Service - Following Exception is displayed on data service console.

	at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at com.ngdesk.data.dao.DataService.getIdsFromGlobalSearch(DataService.java:1351)

we have just accepted chats by admin and started chatting with the agent

This is observed even after restarting graphql and data service several times.

**Screenshot**

![Screenshot from 2021-11-22 15-51-46](https://user-images.githubusercontent.com/89504195/142845659-b5314a73-8e78-4091-8b17-0833955fa309.png)

![Screenshot from 2021-11-22 15-51-38](https://user-images.githubusercontent.com/89504195/142845679-87325d2f-ba7b-4d99-84c1-08b6d8ce6c42.png)

![Screenshot from 2021-11-22 15-51-31](https://user-images.githubusercontent.com/89504195/142845688-a2a1b65a-07cc-4129-aeb0-f159ade4d4f5.png)

**Comment by skatapady** [comment]
- [ ] 14. Web Socket - Application is displaying following  exception in web socket console. Issue was observed when we close that chat widget window.

java.lang.IllegalStateException: The remote endpoint was in state [TEXT_PARTIAL_WRITING] which is an invalid state for called method
	at org.apache.tomcat.websocket.WsRemoteEndpointImplBase$StateMachine.checkState(WsRemoteEndpointImplBase.java:1243)

**Screenshot**

**Illegal State** 

![Screenshot from 2021-11-22 16-07-50](https://user-images.githubusercontent.com/89504195/142846964-c0066ea5-1a96-470e-b5d7-1129c662ad3f.png)

**Null pointer** 

![Screenshot from 2021-11-22 16-11-00](https://user-images.githubusercontent.com/89504195/142847820-8c5fb5cd-4880-4b97-91b0-ef19d6bf4e8e.png)

**Comment by skatapady** [comment]
re opening the issue due to pints mentioned in 10, 12, 13,14

**Comment by skatapady** [comment]
15
- [ ]  15. Issue mentioned in point 10 is not fixed. - We observed that after salutation, line spacing is missing in chat edit layout for admin. FYI screenshot.

**Screenshot**

![Screenshot from 2021-11-24 10-24-31](https://user-images.githubusercontent.com/89504195/143178502-9c257988-bd48-4bd4-aaf1-6b2eb454231d.png)

![Screenshot from 2021-11-24 10-23-37](https://user-images.githubusercontent.com/89504195/143178512-a47255ca-d453-435d-9f71-9c321890e8a1.png)

![Screenshot from 2021-11-24 10-23-27](https://user-images.githubusercontent.com/89504195/143178516-551dd359-bdfa-4821-82e3-b4d3aa1ecd2a.png)

**Comment by skatapady** [comment]
- [ ] 16. **Chat Edit Layout** - Send Button is working only when user clicks on the arrow icon in the button and not the whole button.

**Steps:**

1. post a company with Chats plugin
2. enable chats for admin
3. click on accept chat button
4. open chat-widget and start chatting
5. in chat edit layout for admin , type message
6. click on send message button, make sure you click on edge of the button. (other that arrow icon)

we observed that the chat message was not sent.

**Screenshot**

![Screenshot from 2021-11-24 11-24-25](https://user-images.githubusercontent.com/89504195/143182854-77d47d49-e5b6-43d9-84ca-0c7175f9f1ed.png)

**Comment by skatapady** [comment]
Re opening the issue due to issue mentioned in points 15 and 16

**Comment by ceanugula** [comment]
Both 15 and 16 are resolved.

**Comment by skatapady** [comment]
- [ ]  **POST COMPANY** - i am getting following error while posting a company. Errors are displayed on com[any service console.
{
    "ERROR": "Posting default roles failed, Please contact technical support"
}


**Screenshot**

![Screenshot from 2021-11-25 09-25-06](https://user-images.githubusercontent.com/89504195/143377938-bfca21ff-775d-4053-b5cc-052ffa2f8ed6.png)

![Screenshot from 2021-11-25 09-25-02](https://user-images.githubusercontent.com/89504195/143377945-2c8f374a-34f3-4b0f-925a-4042fe4b46d4.png)

![Screenshot from 2021-11-25 09-24-54](https://user-images.githubusercontent.com/89504195/143377948-ede03ba0-f30c-4155-b1dc-3dc99724df72.png)

![Screenshot from 2021-11-25 09-24-46](https://user-images.githubusercontent.com/89504195/143377952-9ad4daab-2b44-4ea7-aa75-2ce1929982f8.png)

![Screenshot from 2021-11-25 09-24-31](https://user-images.githubusercontent.com/89504195/143377954-7475a34b-3fbd-4dbf-8208-a6a4d7b43d87.png)

**Comment by skatapady** [comment]
- [ ] 18. **Text Editor** - agent/ admin users are able to chat with any editor. 

- we can chat with editor in tickets create/ edit layout.
- We also observed that pre-made response on hitting keyboard enter button, messages are disappearing from the editor. (this is observed in all the editors)

**Steps:**

1. post a company with Chats plugin
2. logon as admin user
3. enable chat for admin
4. click on the accept chat button
5. open widget and start chatting with the agent
6. type a single line and hit enter button.
7. click on tickets --> new button
8. in editor enter single line message and hit enter button
9. observed the chat-widgets

messages sent by tickets module text editor are displayed in the widgets.

verify the behavior when we hit enter button in text editors in Pre-made response, Articles, Campaigns

**Screenshot**

![Screenshot from 2021-11-25 16-31-04](https://user-images.githubusercontent.com/89504195/143429737-e20aefc2-d12e-4724-8942-f88e8cffbc16.png)

![Screenshot from 2021-11-25 16-29-37](https://user-images.githubusercontent.com/89504195/143429756-89b1ee57-0594-465d-a658-5a8a18a7095c.png)

![Screenshot from 2021-11-25 16-26-21](https://user-images.githubusercontent.com/89504195/143429767-17cffa30-216c-4eaf-91ba-0f2146dbeca6.png)

![Screenshot from 2021-11-25 16-26-16](https://user-images.githubusercontent.com/89504195/143429773-13b192b4-2d8e-4c71-99da-89cdb850f03c.png)

**Comment by skatapady** [comment]
re opening the issue due to issue mentioned in point 18

**Comment by sharath-satish** [comment]
> re opening the issue due to issue mentioned in point 18

Fixed this issue

**Comment by skatapady** [comment]
Issue is fixed.

**Comment by skatapady** [comment]
new update working as expected.

![Screenshot from 2021-11-30 15-04-22](https://user-images.githubusercontent.com/89504195/144022043-e98fe837-d7ac-46e9-9c87-c6c12607aced.png)

![Screenshot from 2021-11-30 15-03-42](https://user-images.githubusercontent.com/89504195/144022057-7f976ce9-568b-4408-bf11-e0227b44a95b.png)

![Screenshot from 2021-11-30 14-51-33](https://user-images.githubusercontent.com/89504195/144022061-473cfafe-b45b-43e1-a7d5-c90f2e7b37c8.png)

![Screenshot from 2021-11-30 14-51-30](https://user-images.githubusercontent.com/89504195/144022064-8057e723-0514-4240-98cd-fadd85be06e2.png)
