### ISSUE TITLE
PDFs not displayed in workflows

### ISSUE THREAD

**Issue by knramya** [SubscribeIT/ngDesk#20]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**
- Node Customisation component

**General Description/Overview:**

![image](/uploads/ab7d00231e271cc1902877c6b9e38443/image.png)

![image](/uploads/1c53c8b7599bbd78b596d33c3b8c8b76/image.png)

![image](/uploads/60fb7d7d8240681f13c8f036f64b53e4/image.png)

![image](/uploads/ff5bdfd90b05f83a743ece112b7fd06a/image.png)

**List of Steps:**
- [x] Correct the URL when the api call is happening for first time

**Test Criteria:**
- [x] If the pdf is present it has to be displayed in the dropdown

**Comment by spdhage** [comment]
This **issue** is **fixed**
