### ISSUE TITLE
In Users - Role and Language not displayed

### ISSUE THREAD

**Issue by 11swarajmohanty** [SubscribeIT/ngDesk#201]
Owner: @ssatish
Task Type:

- [ ]  New
- [ ]  Improvement
- [x]  Bug

Projects Affected (Ex. UI, Data-Service):
Components/Services Affected (Ex. Login Component, POST Data API):
General Description/Overview:
In Edit User's details Layout, we observed that the role and language is not displayed on first reload of the user details page. 

List of Steps:

1. Signup as a new user in subdomain.ngdesk.com.
2. Logon to subdomain.ngdesk.com using 'SystemAdmin' Credentials.
3. click on Company settings sidebar menu --> Users --> Click on the created user.
4. Check the Role and Language is not displayed.

Verify whether the Role and Language is displaying on first page reload.
![Screenshot from 2021-09-20 16-27-54](https://user-images.githubusercontent.com/89504233/133991576-bb3d422c-0d5e-4c13-8058-7e57c046ac41.png)

**Comment by spdhage** [comment]
This **issue**  is **fixed**

**Comment by arepallipriyanka** [comment]
[LanguageUpdate.zip](https://github.com/SubscribeIT/ngDesk/files/7233447/LanguageUpdate.zip)

Update program for language

**Comment by vmirji** [comment]
@arvindpal1  test the Update program
