### ISSUE TITLE
Clone feature not working.

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#209]
**Owner:** @karthikbalu1 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**
ngDesk-UI

**General Description/Overview:**
- Clone feature is not working for custom module entry.
- Screenshot:
![Screenshot from 2021-09-23 13-51-33](https://user-images.githubusercontent.com/89620702/134475947-fad472f0-2dc6-412e-a882-3dee94b75196.png)
![Screenshot from 2021-09-23 13-51-38](https://user-images.githubusercontent.com/89620702/134475955-956a182b-2601-414c-a00d-5b780a25cdfd.png)

**List of Steps:**

**Test Criteria:**

- [ ] Cloned entry should be created.

**Comment by unagireddy** [comment]
Created  records and cloned by selecting a checkbox and duplicate record will be generated when we click on clone icon
Checked by deleting the record .
Tested with one_to_one relation ship field
Tested by creating  new module.
issue got fixed no error observed 
/spend 2 hours
