### ISSUE TITLE
Inheritance mapping and items per page button is not aligned

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#216]
**Owner:** @karthikbalu1 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):**  ngdesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):** Field view

**General Description/Overview:**
![Screenshot from 2021-09-30 08-32-51](https://user-images.githubusercontent.com/89504119/135379678-cfff2d23-3d83-405f-b539-c1170405e830.png)

![Screenshot from 2021-10-01 11-34-45](https://user-images.githubusercontent.com/89504119/135573266-fc7454d7-19f7-4a72-99fa-2771d014426d.png)

**List of Steps:**
1. Login to ngdesk.
2. Goto -> modules -> tickets -> fields -> click on any relationship field (Observe the items per page button is not aligned).
3. Click on enable inheritance check box.
4. Click on + icon more than 5 times.
5. Observe the layout.

**Test Criteria:**
Layout must be fixed

**Comment by unagireddy** [comment]
Tested the issue  by creating a one to one relation field  and by clicking enable interface.
tested same with different modules and with new module 
no issue observed

**Comment by unagireddy** [comment]
Testcase 1,2,3 are tested based on the below steps
1.Created the fields with one to one relationship field  and click on enable interface button. and click the enable mapping interface + for multiple times and check the mapping fields  are not overlapped.
2.And for 3rd testcase checked whether the items per page and next page  > and previous page <  everything are aligned in same line or not.
3.tested on fileds layouts ,workflows,tickets, emails,forms,modules,escalations,schedules ,catalogues 
3.Issue got fixed

**Comment by sharath-satish** [comment]
Do not hardcode the height, try to find out a proper fix.

**Comment by unagireddy** [comment]
Same issue have been tested again
By creating a relationship (one-to-one )field for default modules. and selected a enable interface checkbox.
And click the enable mapping interface + for multiple times and check the mapping fields are not overlapped.
And tested for some custom module 
Time Spend 2hours
