### ISSUE TITLE
Change get call to grapql call in API builder

### ISSUE THREAD

**Issue by apriya22** [SubscribeIT/ngDesk#251]
**Owner:** INSERT_TAGGED_OWNER_HERE

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
  ngdesk-UI
**Components/Services Affected (Ex. Login Component, POST Data API):**
  API-builder

**General Description/Overview:**

As a TYPE_OF_USER_OR_ROLE, I want SOME_GOAL so that SOME_REASON_OR_BENEFIT.

**List of Steps:**
* Change get call to grapql call

![Screenshot from 2021-10-19 14-23-20](https://user-images.githubusercontent.com/89504219/137876886-22c8ad07-91b6-43c1-8d29-d1f731a5bd32.png)
![Screenshot from 2021-10-19 14-23-45](https://user-images.githubusercontent.com/89504219/137876893-77f7083c-a7de-4658-968a-aa5b716262d7.png)

**Test Criteria:**
* API request for grapql work properly

**Comment by apriya22** [comment]
Completed
* added include condition in call
* added search 

TODO
* need to make the graphql call fetch values

**Comment by apriya22** [comment]
Completed

* tried multiple ways still curl command for get call isnt working.

TODO

* need to check with sharath

**Comment by sharath-satish** [comment]
> Completed
> 
> * tried multiple ways still curl command for get call isnt working.
> 
> TODO
> 
> * need to check with sharath

Generate the curl command and replace the subdomain to prod and do the api call using curl to check the command

**Comment by apriya22** [comment]
Completed

* couldn't test with a subdomain of prod as prod account server was down

TODO

* need to test the curl command and replace the subdomain to prod and do the api call using curl to check the command

**Comment by apriya22** [comment]
Completed

* tried to curl command 

TODO

* need to check with prod account

**Comment by apriya22** [comment]
Completed

* worked on CSV imports bug

TODO

* need to work on curl commad

**Comment by apriya22** [comment]
Completed

* graphql call returning the response with help of @karthikbalu1  issue was data need to be accepted in string
* added in UI code 
* Need through testing

TODO
* get API builder for graphql ready

**Comment by unagireddy** [comment]
Tested the issue ->company settings > API builder
selected the module with entry.selected get call
selectedall the required file.test the grapql call
tested , different layout  no error in observed 
/spend 4 hours
