### ISSUE TITLE
Company signup improvement

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#266]
**Owner:** @karthikbalu1 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngdesk-rest, ngdesk-comapny-service

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

1. Currently daily company signup job is present in rest service. 
2. It should be migrated to the company service. 
3. New job should be created to perform monthly signup job.
4. The headers required are Company Name, Company Subdomain, First Name, Last Name, Email Address, Phone Number, Timezone, Industry, Signed up for Tickets/Pager/Chat.
5. Email should be sent to: 
    kumar.mukesh@subscribeit.com
    madeleine.fontein@subscribeit.com
    spencer@allbluesolutions.com
    sharath.satish@allbluesolutions.com

**List of Steps:**

- [x] Both jobs should be performed on a daily and monthly basis.

**Test Criteria:**

- [x] Test thoroughly.

**Comment by unagireddy** [comment]
tested the testcase 1,2,3
For 1st TEstcase
posted a company with valid cred . And able to login with out errors

For 2nd testcase
Posted a companies with different Subdomain.
Moved to company services ineclipse--> package com.ngdesk.company.dao -> CompanySignUpJobservice
in sendEmail put log for body
Opened the DailyCompanySignupJob in package com.ngdesk.company.jobs;
Changed @scheduled(fixedRate = 6000) and comment cron Schedule
comment the return of environment check
Take the logs form the consloe 
Check the  total companies posted in  https://www.w3schools.com/tryit/tryit.asp?filename=tryhtml_.
U can see the total companes posted today and last day 11hours companies posted 

For 3rd Testcase
Posted a companies with different Subdomain.
Moved to company services ineclipse--> package com.ngdesk.company.dao -> CompanySignUpJobservice
in sendEmail put log for body
open The MonthlyCompanySignupJob in package com.ngdesk.company.jobs;
Change @scheduled(fixedRate = 6000) and comment cron Schedule
comment the return of environment check
Take the logs form the consloe 
Check the  total companies posted in  https://www.w3schools.com/tryit/tryit.asp?filename=tryhtml_.
U can see the total companes posted for month
issues got fixed
/spend one hour
