### ISSUE TITLE
BUG: Create Create Layout - panel with only one row is created when rows are deleted from previous panel and 'add panel' button s clicked

### ISSUE THREAD

**Issue by skatapady** [SubscribeIT/ngDesk#268]
#### Summary

- [ ] Create Create Layout - Panel with only one row is created when rows are deleted from previous panel and 'add panel' button s clicked. This was observed when were creating a create layout using automation tools.

#### Steps to reproduce

1. logon to subdomain.ngdesk.com using valid admin credentials.
2. Create a new module.
3. create all the fields available for the module. (all the fields )
4. click on Modules --> Books --> Layouts --> Create Layout --> new button.
5. drag and drop all the fields from LHS to RHS. (except for discussion and address fields)
6. click on 'add a panel' button.
7. drag and drop discussion fields to the first row.
8. delete row 6 rows from the panel. (rows 4 to 10 )
9. click on add a panel again 

now observe that panel with only one row is created. (all the rows will be displayed once **add row** button is clicked)

 10  drag and drop city field from LHS to RHS 

observe only city is displayed even though all the address fields are added to the new panel (panel 3)

#### What is the current bug behavior?

now observe that panel with only one row is created. (all the rows will be displayed once **add row** button is clicked)

#### What is the expected correct behavior?

a new panel should be created with ten rows.

#### Relevant logs and/or screenshots

![Screenshot from 2021-10-21 17-05-45](https://user-images.githubusercontent.com/89504195/139044111-65cf0f30-8568-4448-8391-56782c8c8e97.png)

#### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by unagireddy** [comment]
Testing is done for 1,2 testcase 
For testcase 1 
Posted a company with Expenses. Created a address and Discussion field for the Expenses module and added those fields to the crate layout and deleted the rows in the panel.And checked by clicking the Add panel  10rows are created .
For testcase 2.
Updated a already created creat layout by adding fileds.no error is observed while updating 
Issue got fixed
/Spend 2hours
