### ISSUE TITLE
BUG: Register Company - Subdomain is not registered when user clicks on signup button.

### ISSUE THREAD

**Issue by skatapady** [SubscribeIT/ngDesk#272]
#### Summary

Company Signup - On clicking on signup button user is redirected back to 'Signup' page and subdomain is not registered.
This issue is frequently observed.

#### Steps to reproduce

1. navigate to ngdesk.com
2. click on free signup
3. enter all the required fields. (Email, First and Last Name, Phone, password, subdomain)
4. click on signup for free button.

#### What is the current bug behavior?

Subdomain is not registered (or company is not created) and user is redirected back to signup page

#### What is the expected correct behavior?
Company should be registered without any issues and user should be redirected to getting started page.

#### Relevant logs and/or screenshots

![Screenshot from 2021-10-29 08-46-38](https://user-images.githubusercontent.com/89504195/139370220-7d3472b5-e9cb-442a-bdad-05253f42ce13.png)

![Screenshot from 2021-10-29 08-45-36](https://user-images.githubusercontent.com/89504195/139370223-1ab87417-2fe2-4412-83b0-a155c31c7977.png)

![Screenshot from 2021-10-29 08-50-04](https://user-images.githubusercontent.com/89504195/139370311-6b80b27e-fa50-4a24-b467-a5bf99510d89.png)

#### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by kkumar1995** [comment]
![master1](https://user-images.githubusercontent.com/89504408/140053166-c035e5bc-563e-4d84-96c6-64d76fd324fa.png)
- Issue is tested thoroughly and issue is not replicated
![master0](https://user-images.githubusercontent.com/89504408/140053110-6a1f5b01-b75e-41e3-b804-ee9a5e4417bd.png)
![master00](https://user-images.githubusercontent.com/89504408/140053122-e9e4cd20-8563-4e2c-bfc0-b9325e3bd771.png)
![master000](https://user-images.githubusercontent.com/89504408/140053128-c96fcde2-10ec-4bf4-9d27-28783cae0e1f.png)
![master0000](https://user-images.githubusercontent.com/89504408/140053134-fa47cf54-d4bb-44d0-80b2-f9dff29bf794.png)

**Comment by skatapady** [comment]
closing the issue as it is not replicated
