### ISSUE TITLE
The name has to be expanded when the mouse passes over each one in the Tickets module

### ISSUE THREAD

**Issue by shankarshegde** [SubscribeIT/ngDesk#281]
**Owner:** @sharath-satish 

**Task Type:** 
- [ ] New 
- [X] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 

UI

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

In the ticket module, the name has to be expanded when the mouse passes over each one to read them in full and thus be able to choose the one that is needed.

![error ticket 2 ngdesk](https://user-images.githubusercontent.com/89568062/140508304-1bdbcd68-d824-49a3-b91f-d1062743d27c.png)
![image](https://user-images.githubusercontent.com/89568062/140508307-d0696734-fcbb-4073-a420-96853aa142d4.png)

**List of Steps:**

**Test Criteria:**

**Comment by spdhage** [comment]
This **issue** is **fixed**
