### ISSUE TITLE
BUG: Create Custom Module - Error message is thrown when non mandatory one to one relationship field data is empty

### ISSUE THREAD

**Issue by skatapady** [SubscribeIT/ngDesk#282]
#### Summary

**Create Module Data** - Following Error message is thrown when non mandatory **one to one relationship** field data is empty.

The OneBookOneUser may have been deleted, please try again

Issue is observed even for **many to many** relationship field.

#### Steps to reproduce

1. logon to subdomain.ngdesk.com using valid admin credentials
2. create a new module (books)
3. create fields with all the data type. (relationship one to one, relationship one to many, relationship many to many)
4. add the fields to create/ edit list layout
5. add the new module to sidebar.
6. click on books sidebar menu --> new button
7. leave one to one relationship field as empty. (make sure data is entered for all other required fields)
8. click on the save button.

#### What is the current bug behavior?

While creating a module data, Error message is thrown when non mandatory one to one relationship field data is empty
The OneBookOneUser may have been deleted, please try again

#### What is the expected correct behavior?

No Error message should be displayed for non mandatory fields.

#### Relevant logs and/or screenshots

![Screenshot from 2021-11-08 14-44-08](https://user-images.githubusercontent.com/89504195/140718242-8aea9880-7c40-40db-a644-8d100bb5b1c9.png)

#### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by abs-ravi** [comment]
**Completed:-**

- replicated the bug for one to one fields in custom module
- Fixed the bug for one to one fields

**Todo:-**

- Need to test for others relationship field

**Screenshots**
![Screenshot from 2021-11-08 16-59-26](https://user-images.githubusercontent.com/89505098/140734843-0af62978-2e45-426e-9662-66b5fedfff92.png)
![Screenshot from 2021-11-08 16-59-31](https://user-images.githubusercontent.com/89505098/140734848-ddd24e95-3950-4beb-a827-39dd8ac36757.png)
![Screenshot from 2021-11-08 16-59-36](https://user-images.githubusercontent.com/89505098/140734850-9515f43d-b721-4de3-a918-0af255dbebd3.png)

**Comment by unagireddy** [comment]
Created a custom module and add the relationship filed(one to one,one to many,many to many )
Added those to the edit and create layout . And Added Cutom module to the sidebar.
go to new button and create new entry.
Saved the empty fields not entering any data 
no error is observed 

Tested individual relationship field  As well(created a one to one ,one to many ,many to many).
Tested all the modules(product,laptops,asserts..)
Isusue  fixed 
Spend 2 hours
