### ISSUE TITLE
BUG: One to one relationship bug

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#285]
#### Summary

One to one field value is not able to remove.

#### Steps to reproduce

1. Create a field with one-to-one relationship.
2. Store a relationship value and save it.
3. Try to remove that value, it won't be removed.

#### What is the current bug behavior?

1. While performing API call, payload has old data.

#### What is the expected correct behavior?

1. The one to one relationship value should be removed if that value is removed.

#### Relevant logs and/or screenshots

![Screenshot from 2021-11-10 09-45-23](https://user-images.githubusercontent.com/89620702/141049408-78c5f93d-0e7c-4864-85fe-fd17a3a70c09.png)
![Screenshot from 2021-11-10 09-45-27](https://user-images.githubusercontent.com/89620702/141049416-6511a71f-6655-47e3-8876-3e4a88a49f02.png)

#### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by apriya22** [comment]
Completed

* added code for Many to one and one to one
* need to test all scenario

**Comment by karthikbalu1** [comment]
It's not a bug. The one to one value can be updated but it can't be removed.
