### ISSUE TITLE
Not null, not empty annotations are missing for required fields

### ISSUE THREAD

**Issue by sharath-satish** [SubscribeIT/ngDesk#288]
Not null, not empty annotations are missing for required fields

_Originally posted by @sharath-satish in https://github.com/SubscribeIT/ngDesk/pull/227#discussion_r750853704_

**Comment by unagireddy** [comment]
Tested the issue
If we remove the seperator. it will through error ""ERROR": "CSV_FORMAT should not be null"
if we not specify any file type then the error is observed be ""ERROR": "FILE_TYPE cannot be blank"
And if we not specify any filename then error "ERROR": "FILE_NAME cannot be blank"
no eror observed
/Spend 3 hours
