### ISSUE TITLE
Font mismatch

### ISSUE THREAD

**Issue by sharath-satish** [SubscribeIT/ngDesk#290]
**Owner:** INSERT_TAGGED_OWNER_HERE

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

![image](https://user-images.githubusercontent.com/89503138/142135152-0b7b9664-97f0-4ff6-820e-6b0d51fdf1b4.png)

- Material font must be used

**List of Steps:**

**Test Criteria:**

**Comment by vishalmeda** [comment]
Test case:
1) Run ng-deskUI locally. Open dev1.ngdesk.com
2) Go to company settings->Module Settings->import module data from file
3)choose module-> Upload the file
4) click on the file->click on the lines failed, In Note font must have changed

**Comment by unagireddy** [comment]
Issue got fixed
Tested by importing the csv file with invalid data. and observed the font size 
/time spent 1 hour
