### ISSUE TITLE
Relationship field of type 'One to many' should be removed from conditions fields drop down

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#3]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

Create/ Edit List Layout - We observed that when relationship field of type 'One to many' is selected as conditions. Application is returning following error when we select any (it is observed for all the operators) available operator. PFA screenshot.

Operator is Invalid.

Relationship field of type 'One to many' should be removed from conditions fields drop down.

Issue needs to be verified in Validations, Workflow, SLA, Fields, List Layout, Edit Layout, Create Layout, Dashboards, ActionItems, Email Lists. (wherever conditions fields will be displayed)

**List of Steps:**

1. navigate to subdomain.ngdesk.com
2. create a new module Books 
3. create field with following data types

Relationship field with one to many , text, autonumber, discussions, pick lists.

4. create a list/ edit/ create layouts 
5. click on Modules --> books --> layout --> list layout --> new button.
6. select conditions as one to many field created in step 3.
7. select valid operator and data.
8. click on save button. (make sure data for other required fields are entered/ selected)

verify the error message.

**Screenshot**

![1](https://user-images.githubusercontent.com/89504119/130950762-2d2e00d5-e9d1-46da-94a3-e6ba008996b0.png)

**Comment by unagireddy** [comment]
issue fixed 
/spend 3 hours
