### ISSUE TITLE
Add Save and Continue for create layouts

### ISSUE THREAD

**Issue by sharath-satish** [SubscribeIT/ngDesk#302]
**Owner:** @sharath-satish 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-UI
- 
**Components/Services Affected (Ex. Login Component, POST Data API):**
- render detail new component

**General Description/Overview:**

As a user, I want to save and be in the edit page when I create a new entry.

**List of Steps:**

**Test Criteria:**

**Comment by skatapady** [comment]
- [ ] 2. **Create Tax (Expense Module)** - Duplicate records are created when we create new tax on clicking on the 'save and continue' button and in edit layout again click on 'save and return' button.

**Steps**

1. post company  wiih chat, expense plugins.
2. logon as admin user
3. click on Expenses --> Taxes --> new button
4. enter valid details for all the required fields.
5. click on 'save and continue' button
6. In the edit layout, click on 'save and return' button.

we observed that duplicate records are created.

**Screenshot**

![Screenshot from 2021-11-23 11-31-34](https://user-images.githubusercontent.com/89504195/142977751-1937261b-15bb-42ed-9886-f2e5e3924771.png)

![Screenshot from 2021-11-23 11-31-26](https://user-images.githubusercontent.com/89504195/142977754-37138c5d-559e-431d-8d92-0e00d6d201ba.png)

![Screenshot from 2021-11-23 11-31-13](https://user-images.githubusercontent.com/89504195/142977759-ae48f72b-7f68-458f-941a-6385db98fd9b.png)

**Comment by skatapady** [comment]
Re opening the issue.

**Comment by skatapady** [comment]
issue is fixed.
