### ISSUE TITLE
BUG:List Formula - Create/ Edit Layout is not loading on adding field with data type as 'List Formula'

### ISSUE THREAD

**Issue by skatapady** [SubscribeIT/ngDesk#304]
#### Summary

Create/ Edit Layout is not loading on adding field with data type as 'List Formula'. Following error is displayed on the console.

TypeError: Cannot set properties of undefined (setting '0')
    at C.buildTemplateForGridLayout (main.9d35e18dea2756d547f0.js:1)
    at C.getLayoutForListFormula (main.9d35e18dea2756d547f0.js:1)
    at /98591.5db230308207dab42a80.js:1
    at Array.forEach (<anonymous>)
    at E.buildTemplates (/98591.5db230308207dab42a80.js:1)
    at M0.initializeLayout (/98591.5db230308207dab42a80.js:1)
    at R._next (/98591.5db230308207dab42a80.js:1)
    at R.__tryOrUnsub (main.9d35e18dea2756d547f0.js:1)
    at R.next (main.9d35e18dea2756d547f0.js:1)
    at w._next (main.9d35e18dea2756d547f0.js:1)

#### Steps to reproduce

1. logon to subdomain.ngdesk.com
2. click on modules --> Products --> fields --> new button
3. enter valid display name
4. select data type as 'List Formula'
5. click on the next button.
6. enter valid name.
7. click on product name + blank space + product code field
8. click on the save button.
9. add the field to create / edit layout.
10. click on product --> new button

we observed that create layout is not loaded.

11. click on existing product

we observed that the edit layout is not loading.

12. select the existing data in product list layout
13. click on the clone button.
14. in the confirm dialog, click on the yes button

we observed that clone product layout is not loaded.

#### What is the current bug behavior?

Create/ Edit Layout is not loading on adding field with data type as 'List Formula'. 

#### What is the expected correct behavior?

Create/ Edit Layout should be loaded with all the fields in the layouts (as designed) without any issues.

#### Relevant logs and/or screenshots

![Screenshot from 2021-11-23 13-13-12](https://user-images.githubusercontent.com/89504195/142987008-c3e4147c-eae3-4099-95c6-4ce788291092.png)

**Comment by apriya22** [comment]
Completed
* Was not able to replicate the bug but the bug is when we are placing the list formula field and it gets accepted to already 
the placed field also, working on that

![Screenshot from 2021-11-23 16-04-40](https://user-images.githubusercontent.com/89504219/143009037-7cc257b3-251f-4b60-8cc0-76998d2b91f0.png)

TODO
*  when list formula is placed in edit and creat layout , it shouldn't throw error in console 
* placed on wrong placed throw error in banner message

**Comment by apriya22** [comment]
Completed

* Added code in detail layout compoenent.ts

TODO

* Need thorough testing

**Comment by apriya22** [comment]
TO run the application

* run ngdesk-web locally and ngdesk-Rest

**Comment by unagireddy** [comment]
Tested by creating a LISTFORMULA field and added to the edit and create layout.The filed should be draged into panel which is not lessthan 4 rows. if we drage for 3 or 2 or 1 it throws an error(filed can be dropped at this position). and checked whether the field entry is displayed on the record or not.
no concole error
