### ISSUE TITLE
BUG: Edit Chats - Table is not properly Formated

### ISSUE THREAD

**Issue by skatapady** [SubscribeIT/ngDesk#309]
#### Summary

In Edit Chats Layout, we observed that table is not properly formatted.

#### Steps to reproduce

1. post a company with Chats plugin
2. logon as admin user
3. enable chats for agent
4. logon as agent and click on the accept the chats
5. open chat widget and start chatting with the agent
6. prepare a table with more than 4 columns with some test data and 
7. click on send chats button

verify the formatting of the table.

#### What is the current bug behavior?

In Edit Chats Layout, we observed that table is not properly formatted.

#### What is the expected correct behavior?

In Edit Chats Layout, we expect data in table to be properly formatted.

#### Relevant logs and/or screenshots

![Screenshot from 2021-11-30 09-18-03](https://user-images.githubusercontent.com/89504195/143984395-0f61293b-f4e6-4521-b58d-ea062908e78c.png)

![Screenshot from 2021-11-30 09-14-21](https://user-images.githubusercontent.com/89504195/143984399-4bbfb9f4-727d-4f04-9b05-e08f9782d923.png)

![Screenshot from 2021-11-29 16-06-33](https://user-images.githubusercontent.com/89504195/143984403-2281dd95-d2da-49dd-8546-fc26bc616c23.png)

![Screenshot from 2021-11-29 16-05-01](https://user-images.githubusercontent.com/89504195/143984404-2545f187-6e52-470f-83a4-33a4ea742a64.png)

**Comment by NydileGR** [comment]
Completed:
-  Replicated the bug and gone through code

ToDo:
- need to fix it

**Comment by NydileGR** [comment]
Completed:
- added scrollbar for formatting the table.

ToDo:
- testing

**Comment by unagireddy** [comment]
Issue got resloved 
created a table with rows and columns  on the chat and cheked the same is formulated on the chatwidget
issue got fixed
/spend 2 days
