### ISSUE TITLE
BUG:Signup shown in login pages

### ISSUE THREAD

**Issue by sharath-satish** [SubscribeIT/ngDesk#311]
#### Summary

Signup button visible even when enrolment is turned off

#### Steps to reproduce

- Login to ngdesk -> Company settings -> Security section -> General Settings -> Turn off the enrolment

#### What is the current bug behaviour?

- Signup button is shown in login page

#### What is the expected correct behaviour?

- Signup line in the login page must be hidden

#### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/89503138/144784883-dd2e3b50-1efd-486e-a60f-aee1ea3b815f.png)

![image](https://user-images.githubusercontent.com/89503138/144784944-67342bf8-7b1f-4994-9240-9aab7fde5333.png)

#### Possible fixes

- Donot show the text "Dont have account signup"

**Comment by unagireddy** [comment]
tested  based on the following steps
Posted a company . if i unselect the checkbox of Allow users to sign up in security present in company settings
once u save and logout then u can observe "Dont have account signup"  wont be in loginpage
If u select "Allow users to sign up " checkbox " logout by saving it. If you try to login you can clearly observe"Dont have account signup"   
issue got fixed 
/spend 2 hours
