### ISSUE TITLE
Csv import improvements

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#312]
**Owner:** @karthikbalu1 

**Task Type:** 
- [ ] New 
- [x] Improvemnt 
- [ ] Bug

**Projects Affected (Ex. UI, Data-Service):** 
ngdesk-web, ngdesk-data

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

- Non-editable condition should be removed while importing CSV file.
- Exception handle for default fields.

**Test Criteria:**

- [x]  Test whether all the fields importing properly.

**Comment by unagireddy** [comment]
Issue got fixed.
created a users with different roles (Accountant,system admin, account manager).
importated tickets with tickets.csv file . and selected the subject, for subject  message, for message and requester for requestor field.and imported the file
go to tickets in sidebar and open the entries that are generated by csv . check any values selected for default fields
no error observed 
/spend 3 hours

**Comment by unagireddy** [comment]
Issue got fixed.
created a users with different roles (Accountant,system admin, account manager).
importated tickets with tickets.csv file . and selected the subject, for subject message, for message and requester for requestor field.and imported the file
go to tickets in sidebar and open the entries that are generated by csv . check any values selected for default fields
and tested with default fileds like  date created date updated,last updated by, effective from
no error observed
/spend 3 hours
