### ISSUE TITLE
BUG: List Time stamp issue in list layout

### ISSUE THREAD

**Issue by shankarshegde** [SubscribeIT/ngDesk#319]
#### Summary

When creating a ticket I assign a date and time but when displaying the list in the "Enlace Soportes" field of the "Instalaciones" module, the time appears changed, it is 5 hours behind (our time zone is -5), it seems that it is delayed. This is only seen in this list because in the others it comes out correctly.  

#### Steps to reproduce

Update a date and time in the edit layout, save the ticket and then look for the same field in the list layout. It shows a different time than the one which you have specified.

#### What is the current bug behavior?

In list layout, in the date & time field It shows a different time than the one which was selected in the edit/create layout in the same field.

#### What is the expected correct behavior?

It should show the same time in the list layout which was selected while creating/editing the ticket in the date & time field.

#### Relevant logs and/or screenshots

![image (1)](https://user-images.githubusercontent.com/89568062/146503070-6ef8c033-6c37-4d2e-9c79-dfa0eebd6157.png)

![image](https://user-images.githubusercontent.com/89568062/146503081-d77ba24c-34e3-412e-a8e7-aaba870ff8f7.png)

ngDesk Support ticket#**7260**
Ticket Link - https://support.ngdesk.com/render/5f68d2d296151b30f85b4f12/edit/61bb5f9352ad001c7c256e46 

#### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by karthikbalu1** [comment]
I tried to replicate the issue, but I couldn't replicate it. Spoke with Shankar, even he was not facing any issue. Now Shankar would interact with user itself, and ask whether the issue still exists, if the issue exists he will ask for which scenario it's breaking.

**Comment by unagireddy** [comment]
Tested based on the steps
Created  date,date/time and time fields added same to the edit create and web layout
in sidebar requried moudle add the requried data over the date datetme and time.
go to module create one to many relation field and add the module where the date time ND datetime fields were created
add same to relationship filed to edit create .
go to side bar go to requried module  open any existing record and open the attachment image on onetomany .and check the date time nad datetime is same as same where u have cretaed in module
no eror is observed
/spend 3 hours
