### ISSUE TITLE
user name logo bug

### ISSUE THREAD

**Issue by ceanugula** [SubscribeIT/ngDesk#327]
#### Summary

* User name logo is not getting displayed for the first message

#### Steps to reproduce

- post a company with chats plugin and login as a system admin
- In company->chat settings add system admin team save it and click on accept chats 
- In another window open chat widget and start chat by providing the required details
- Do a first message from customer side and go back to agent side and check.

#### What is the current bug behavior?

- user name logo is not getting displayed for first message.

#### What is the expected correct behavior?

- It has to display user name logo for first message as well.

#### screenshots

![image](https://user-images.githubusercontent.com/89504492/148046455-5e63fe9d-8b1a-4a1b-adc9-0ac27628a3e2.png)

**Comment by AyushAllBlue** [comment]
Update program :- 

[ChatEditLayout.txt](https://github.com/SubscribeIT/ngDesk/files/7814244/ChatEditLayout.txt)

**Comment by unagireddy** [comment]
Tested based onthe steps
Posted a new company.added systemadminto chatsettings.
opened chat widget on other windowm and start chat with requried field
send a message from customer side and go back to agent and check it.
user logo is displayed. 
Note: customer and agent mail id should be different.if both r same everything will be one side
/spend 3 hours

**Comment by AyushAllBlue** [comment]
Update program : -

[UserNameLogoFix.txt](https://github.com/SubscribeIT/ngDesk/files/7991679/UserNameLogoFix.txt)

**Comment by unagireddy** [comment]
tested the issue
everything is wrking fine as before
/spend 3 hours
