### ISSUE TITLE
BUG: Kb articles font

### ISSUE THREAD

**Issue by karthikbalu1** [SubscribeIT/ngDesk#332]
#### Summary

The kb articles is using default font from browsers.

#### Steps to reproduce

Go to KB articles > general > FAQ

#### What is the current bug behavior?

Default font being used.

#### What is the expected correct behavior?

Angular material font should be used.

#### Possible fixes

Add mat body in render article component.

**Comment by karthikbalu1** [comment]
Requirement update: 
Check whether the font can be changed in tiny mce by default.

**Comment by AyushAllBlue** [comment]
- Added default font and roboto font in drop down dynamically in tinymce config file.
- Tested fonts in edit layout.
- Fonts is being set as the body font in edit layout.
- Tested by typing the font in tinymce and checked whether it is the set font or not.

![Screenshot from 2022-01-10 15-12-37](https://user-images.githubusercontent.com/89504119/148745335-7c575ff9-c939-476a-8b08-10f9a105c987.png)

**Comment by unagireddy** [comment]
Tested the issue based on the steps
Open any article in general under knowledge base. check the font in the article whether the font is roboto
no error observed
Created new article and observed font is robot by default texted .observed the text which is texed is roboto
no error is observed
/spend 3 hours
