### ISSUE TITLE
BUG:Report download URL is broken

### ISSUE THREAD

**Issue by shankarshegde** [SubscribeIT/ngDesk#337]
#### Summary

The report download URL is broken and the time is separated as shown in the attached screenshot due to which the users are unable to download the report and getting an error message stating -  **{"ERROR":"Internal server error, please contact support"}**

#### Steps to reproduce

Log in to your ngDesk account>Click on Reports from the sidebar menu>Click on **New** button >create a new report> fill in all the fields and select required module, fields, filters, etc. Once done, click on **Download** button at the top right corner. You will receive an email with the link to download the report along with URL below that in case if the link didn't work. If you click on the URL, you will receive an error. Also, the time of the report which is available in the URL is separated. This is causing the issue.

(How one can reproduce the issue - this is very important)

By clicking on the **URL** available in the Reports email which you will receive upon clicking on **Download** button inside any report under ngDesk.

#### What is the current bug behavior?

As soon as you click on URL, you will receive an error - **{"ERROR":"Internal server error, please contact support"}**

#### What is the expected correct behavior?

The URL should not contain an space or the text in the URL should not be separated. User should be able to download the report successfully by clicking on the **URL**.

#### Relevant logs and/or screenshots

![Report URL](https://user-images.githubusercontent.com/89568062/148744318-d1eaff33-5446-4ed9-be63-8094d89c9cac.jpg)

#### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by abs-ravi** [comment]
**Completed:-**

- able to replicate bug
- added % between date and time in reportname 

ToDo:-

- need to change html template for report_download_email.html (URL in template is not hyper link)
- Need confirmation for changing HTML template @karthikbalu1

**Comment by abs-ravi** [comment]
**Completed:-**

- Removed spaces from report Url
- Did changes in template.
- tested email body locally

**Screenshots:-**
![Screenshot from 2022-01-13 14-25-38](https://user-images.githubusercontent.com/89505098/149299237-4a623ec1-2ede-4563-8389-dc32de61b3b7.png)
![Screenshot from 2022-01-13 14-25-44](https://user-images.githubusercontent.com/89505098/149299249-b0fdcf0d-b0ff-46a9-bc00-f01e3362b89d.png)

**Comment by unagireddy** [comment]
Tested the issue by posting a company
copied the path of an file directory pasted those on the report and collector file in graphql.
go to dev1.and generate a report and download it .
once we download any filea html code wil be genrated on the consule .copy the console and pasted on the link:https://www.w3schools.com/tryit/tryit.asp?filename=tryhtml_hello..
once we click on the url that which is dowmload on the tryiteditor  we are able to download the report successfully by clicking on the URL.
no error observed 
/time 2 hours
