### ISSUE TITLE
BUG: Create/ Edit Catalogue - User is able to create a catalogue without forms

### ISSUE THREAD

**Issue by skatapady** [SubscribeIT/ngDesk#349]
#### Summary

Create/ Edit Catalogue - User is able to create a catalogue without selecting any forms/ service catalogue.

#### Steps to reproduce

1. Post  a new company.
2. login as admin user.
3. click on Company Settings --> Catalogue --> new button.
4. enter valid data in name and description field.
5. select valid Visible to teams as Global.
6. click on the 'save' button (make sure no forms are selected)

#### What is the current bug behavior?

User is able to create a catalogue without selecting any forms/ service catalogue.

#### What is the expected correct behavior?

User should select at-least one **forms/ service catalogue** while creating a Catalogue.

#### Relevant logs and/or screenshots

![Screenshot from 2022-01-27 13-02-49](https://user-images.githubusercontent.com/89504195/151312091-8ccdcfd7-6bce-44eb-aa1e-3db24b86c66b.png)

#### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by unagireddy** [comment]
issue has tested by posting a company cretaed a forms for the modules. in company settings go to calatouge add the module with forms. no error observed 
/time 2 hours
