### ISSUE TITLE
BUG: Problem with an auto number field

### ISSUE THREAD

**Issue by shankarshegde** [SubscribeIT/ngDesk#350]
#### Summary

I need to assign a consecutive number and I need it to start at a number other than 1. I created an auto number field but it doesn't respect the starting number I set and always starts at number 1.

#### Steps to reproduce

Create a custom field with **Auto Number** Data type.  Type in a random number other than 1 in the **Starting Number** field while creating the new field. Add this field onto either **Web List Layout** or **Web Edit Layout**, or onto both the layouts. 

#### What is the current bug behavior?

Once added onto the layout, the newly created Auto Number field starts from **1** irrespective of the number that you have chosen to start from. 

#### What is the expected correct behavior?

The **Auto Number** field should start from the number that we have chosen in the **Starting Number** field while creating it.

#### Relevant logs and/or screenshots

![image](https://user-images.githubusercontent.com/89568062/151341556-c17a1d01-bf1e-47ce-8b5d-3cbd7d04728c.png)

#### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by unagireddy** [comment]
Posted a company and created a autonum filed and set default value as 100 in tickte module and added the field to list layout. in listlayout go to Systemadmin of allticktes . go ticktet in sidebar create a new ticket and go to all ticktes and observe the default value.Create a new ticket and repeart the sawm and check the default was incremented.
create more autonum field with some values as 500 600 700 and repeart the process . no error observed
/time 3 hours
![JAnuary 28th 2022---2022-01-28 14-21-26](https://user-images.githubusercontent.com/89505057/151518340-89e654d4-bcf0-4e61-8232-93fe3e56e5c7.png)
