### ISSUE TITLE
Contacts edit layout issue

### ISSUE THREAD

**Issue by knramya** [SubscribeIT/ngDesk#41]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 
- ngDesk-UI

**Components/Services Affected (Ex. Login Component, POST Data API):**
- Render detail

**General Description/Overview:**
![Screenshot_from_2021-08-04_09-30-00](/uploads/5312b824505338f16570d706cf4b6919/Screenshot_from_2021-08-04_09-30-00.png)

**List of Steps:**
- [ ] Resolve the console bugs

**Test Criteria:**
- [ ] Make sure the entry can be saved

**Comment by apriya22** [comment]
* Issue have been fixed in this branch

https://github.com/SubscribeIT/ngDesk/issues/140
