### ISSUE TITLE
Picklist issue and layout cards alignment

### ISSUE THREAD

**Issue by AyushAllBlue** [SubscribeIT/ngDesk#45]

**Comment by AyushAllBlue** [comment]
Issue is fixed already.

Screenshots :- 

![Screenshot from 2021-08-31 08-48-43](https://user-images.githubusercontent.com/89504119/131436312-8782ab30-fc97-46b1-9777-95a892da4b8e.png)
![Screenshot from 2021-08-31 08-48-54](https://user-images.githubusercontent.com/89504119/131436323-c7df07e8-6c83-48a3-8d57-45a5a8346266.png)
![Screenshot from 2021-08-31 08-49-27](https://user-images.githubusercontent.com/89504119/131436329-7cadfc7d-f2d0-46bf-96a0-b4f069089182.png)

**Comment by unagireddy** [comment]
Issue is not getting replicating below steps while testing
1.Cards aligned in all the modules properly even the layout cards 
2. Picklist and picklist (multi select ) is tested without any data and error is population.

/spend 45mints

**Comment by karthikbalu1** [comment]
Issue is not being replicated, so closing the issue.
