### ISSUE TITLE
Create Tickets - Tickets are not created when chronometer field with default value is created and not added to Create Layout

### ISSUE THREAD

**Issue by knramya** [SubscribeIT/ngDesk#69]
**Owner:** @ssatish 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

**Create Tickets** - Application is returning following error message when field with data type **'chronometer'** is created with **any default value** (5m) without adding it to **create/ edit** layout.

chronos is not a valid chronometer value, please try again

We also observed that email sent by user is not logged as ticket when chronometer field is created with default value.

Issue is observed in **'Custom Module'** also.

**List of Steps:**

1. login to subdomain.ngdesk.com using valid 'SystemAdmin' credentials.
2. In tickets module, Create a field with data type as 'chronometer' with any default value (4m) (**make sure required is not selected**) (make sure field with data type as 'chronometer' is not added to create/ edit layout)
3. Click on tickets sidebar menu.
4. click on new button.
5. enter valid data for subject and message body (and other required fields)
6. click on 'save' button.
7. send an email from unregistered email address.

verify whether email is received.

**Screenshots:**
![Screenshot_from_2021-04-08_17-41-47](https://user-images.githubusercontent.com/89504314/130953420-92818c33-7fce-419e-9702-6bc3f68da853.png)

![Screenshot_from_2021-04-08_17-41-52](https://user-images.githubusercontent.com/89504314/130953424-47ce4230-4549-42f7-81e9-b0852b438a82.png)

![Screenshot_from_2021-04-09_08-41-44](https://user-images.githubusercontent.com/89504314/130953427-0ae4d06f-9d22-4fa6-893e-e262c3f8f500.png)

![Screenshot_from_2021-04-09_10-05-22](https://user-images.githubusercontent.com/89504314/130953433-0639a598-4070-4549-bfd5-e30d98ea3194.png)

**Test Criteria:**

**Comment by arepallipriyanka** [comment]
33 issue changes are required to test this issue, so that i have added this fixes with 33 issue and tested, everything working fine. issues are fixed
