### ISSUE TITLE
Bugs ngdesk 1

### ISSUE THREAD

**Issue by CHINMAYJAIN03** [SubscribeIT/ngDesk#74]
**Owner:**

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** ngdesk

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

**List of Steps:**
1. Contact module - Create/ Edit is not working. (looks like issue with field UUID)
2. Users drop-down is working but now only one data is displayed in tickets modules (for rest of the modules issue still exists)
3. Role-Layouts - List Layout is not working.
4. SLA - Create SLA is still not working (violation is not loading)
5. Company Registration - Welcome Email, Email Verification , Resend Email Verification Emails and forgot password are not working.
6. Delete Roles is not working
7. Report - csv is not generated and downloaded report is empty.
8. Accept/ Reject Chats can be removed from profile drop-down.
9. Getting Started for Chats - It is not working and can be removed.
10. Forms - (Create/ Edit) - Forms is still not working.

**Test Criteria:**

**Comment by 11swarajmohanty** [comment]
Completed: Tested all the issue points one by one and found some issue points are resolved earlier. For company registration, the forgot password submit is not working. I tried fixing the url, but didn't work. Todo: Need to fix the correct url for submitting the forgot password.

**Comment by 11swarajmohanty** [comment]
Closes #74 as all the issue points are tested and working fine.
