### ISSUE TITLE
Download Reports issue

### ISSUE THREAD

**Issue by CHINMAYJAIN03** [SubscribeIT/ngDesk#76]
**Owner:** @npanicker 

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**
Application is returning 500 Internal server error on the console on clicking on the ‘Download’ button. We also observed that downloaded report is empty.

polyfills-es2018.4bd66fded4b22ec2f2d8.js:1 POST https://test81ksb3.ngdesk.com/ngdesk-rest/ngdesk/reports/newRepTickets/generate?authentication_token= 500

{"timestamp":1601881316632,"status":500,"error":"Internal Server Error","message":"class java.lang.String cannot be cast to class java.util.Date (java.lang.String and java.util.Date are in module java.base of loader 'bootstrap')","path":"/ngdesk/reports/newRepTickets/generate"}

**List of Steps:**

**Test Criteria:**

**Comment by spdhage** [comment]
This **issue** is **already** fixed , in **production account** its not **replicated**
