### ISSUE TITLE
Create/Edit ticket issues

### ISSUE THREAD

**Issue by CHINMAYJAIN03** [SubscribeIT/ngDesk#80]
**Owner:** INSERT_TAGGED_OWNER_HERE

**Task Type:** 
- [ ] New 
- [ ] Improvemnt 
- [x] Bug

**Projects Affected (Ex. UI, Data-Service):** 

**Components/Services Affected (Ex. Login Component, POST Data API):**

**General Description/Overview:**

**1.** **Create Ticket** – on Selecting data from requestor field, application is returning following error on the console. Same issue is observed when an Asignee is added (using user invite) in both the Create/ Edit Tickets Layout.

TypeError: Cannot convert undefined or null to object

**2.** **Create Ticket** – Following error is displayed on the console on clicking on ‘add’ button beside requestor field and new Add contact pop-up window is displayed.
![Screenshot from 2021-08-26 16-36-53](https://user-images.githubusercontent.com/89504211/130952239-e33e5948-bccd-478a-8b42-bff59a05ca49.png)

**3.** **Create/ Edit Ticke**t - Once an ‘Assignee’ is added by clicking on ‘add’ button for a ticket. When user logs a second ticket. Newly added asssignee (created by previous ticket) is not displayed in the dropdown. So, every time we need to create new assignee.

**4.** **Edit Tickets** – Valid data entered in 'Chronometer’ field ‘Time Spent’ is not ‘displayed’ in Edit Layout. Sometimes it is not displayed until the status is updated as ‘Open’ and ticket data is saved at least once after updating the status to 'Open’ from ‘New’.

Same issue is observed when ticket is updated using bulk update feature.

**5.** **Create/ Edit Tickets** – label for text editor is empty. (only empty circle is displayed). We can fill it with image/ icon.

**6.** **Create Tickets** – While creating contact data by clicking on ‘add’ button in ‘Requestor’ field. We observed following issues.

a. ‘null’ value is displayed below phone number field. 

b. When browser’s window is restored, we observed that fields are overlapping on each other. All the fields should be aligned properly irrespective of window size.

**7.** While creating contact data by clicking on ‘add’ button in ‘Requestor’ field. We observed following issues.

a. Application is not saving/ creating contact data on clicking on ‘done’ button. We have entered all the required fields. Looks like phone number entered was invalid (or US phone is not getting validated properly). Please refer below json POST REST API request.

---------- URL

https://test81ksb3.ngdesk.com/api/ngdesk-data-service-v1/modules/5f68d2d296151b30f85b4f16/data?is_trigger=false&authentication_token=

---------- JSON request body -----

{"FIRST_NAME":"Sita","LAST_NAME":"n","ACCOUNT":{"DATA_ID":"5f7aa2c7ace3343b7fc5e512","PRIMARY_DISPLAY_FIELD":"ngdesk.com"},"COUNTRY":"United States","TIMEZONE":"America/Puerto_Rico","TEAMS":[{"DATA_ID":"5f7aa2c7ace3343b7fc5e504","PRIMARY_DISPLAY_FIELD":"Global"}],"PHONE_NUMBER":{"COUNTRY_CODE":"us","DIAL_CODE":"+1","PHONE_NUMBER":4696480698,"COUNTRY_FLAG":"us.svg"},"FULL_NAME":"Sitan"}

----------------------

b. In the above REST API request in json format, we observed that ‘Full_NAME’ field does not have space.

**8.** Tickets - After adding a new field to Layouts, we need to click on browser’s ‘refresh’ button to view the updated layouts with the new fields. This issue is observed for Create/ Edit/ List and Detail Layouts.

**List of Steps:**

**Test Criteria:**

**Comment by AyushAllBlue** [comment]
Issue is not replicated in create/edit ticket layout because the requestor add button is disabled now.

![Screenshot from 2021-09-02 09-31-10](https://user-images.githubusercontent.com/89504119/131779851-43856282-5d4c-4584-9b03-c2bb9d3c739a.png)

**Comment by sdthengil** [comment]
Issue is not replicating.while creating a new ticket "add" button of requester field is disabled.

issue is fixed.

/spend 1h

**Comment by karthikbalu1** [comment]
Issue is fixed so closing the issue.
