### ISSUE TITLE
Render detail layouts improvements

### ISSUE THREAD

**Issue by CHINMAYJAIN03** [SubscribeIT/ngDesk#87]
Do not refer to old issues related to this task. All changes should be done in this issue.

![Screenshot from 2021-08-26 16-40-03](https://user-images.githubusercontent.com/89504211/130952643-6b9378fd-6617-4ab2-8f5e-9eb93e805476.png)

**Comment by apriya22** [comment]
* Already its fixed

**Comment by karthikbalu1** [comment]
Issue is already fixed, so closing the issue.
