### ISSUE TITLE
Edit Button Field - Unable to add 'new trigger' to a button when existing trigger is deleted

### ISSUE THREAD

**Issue by CHINMAYJAIN03** [SubscribeIT/ngDesk#97]
#### Summary

In Edit field Layout for field with data type as 'button', we observed that once the existing 'trigger' is deleted the user is unable to update the trigger with a new trigger as 'trigger' drop down is read-only.

PFA video

#### Steps to reproduce

1. Navigate to mydomain.ngdesk.com using your Chrome browser.
1. Click on 'Login' button.
1. Login with valid admin credentials.
1. Click on 'Modules -> Custom module -> Fields -> New button'
1. enter valid data in name field. (sendButton)
1. select data type as 'Button'.
1. Click on 'next' button.
1. Make sure no triggers are created for this module.
1. Click on the 'please click here to create a trigger' link.
1. In the new tab, make sure valid data is entered/ selected for Name, Description, Trigger Types and Order fields.
1. Click on 'plus' icon under 'Actions' (beside 'Perform these Actions' label)
1. select 'Select an Action' as 'Send Email'
1. Select valid data from 'From' field
1. Enter valid data in To, Subject and Body Fields.
1. Click on the 'save' button. (trigger1)
1. select the new trigger in the above steps in the 'trigger' drop down.
1. click on the 'save' button
1. Click on the 'Trigger' menu link.
1. delete the above created trigger  (trigger1)
1. Click on the 'field' menu link.
1. In Field List Layout, click on the above create field (sendButton)

1. PFA video for steps.

#### What is the current bug behavior?

Unable to add 'new trigger' to a button when existing trigger is deleted

#### What is the expected correct behavior?

In Edit fields Layout, Users should be able to update the triggers for field with data type as 'button'.

#### Relevant logs and/or screenshots

Video 

https://user-images.githubusercontent.com/89504211/130953080-f9954b5e-08c5-44a0-a195-c029772dad9e.mp4

#### Possible fixes

(If you can, link to the line of code that might be responsible for the problem)

**Comment by unagireddy** [comment]
Tested the issue 1 and 2
created field with button data type and added workflow for it and saved
deleted the workflow which is added to the entry
Again open the existing entry and check whether the workflow is deleted and add a new workflow for it
No error is observed
time taken 2 hours
