### ISSUE TITLE
Getting Started improvements

### ISSUE THREAD

**Issue by CHINMAYJAIN03** [SubscribeIT/ngDesk#98]
* [x]  Needs to look exactly the same across Firefox, Chrome, and Safari. Notice the percentage of completion is not aligned in the center of the circle in firefox. There is also a bigger gap in between the layout

Firefox:

![Screenshot from 2021-08-26 16-45-34](https://user-images.githubusercontent.com/89504211/130953353-57ca9572-8bfc-47cf-aba9-257ac9c8055a.png)

Chrome:

![Screenshot from 2021-08-26 16-46-02](https://user-images.githubusercontent.com/89504211/130953403-065a423d-8342-4556-971d-3f61dba5b5b6.png)

**Comment by apriya22** [comment]
* issue is fixed in given link
https://github.com/SubscribeIT/ngDesk/issues/38
